version: "3"
services:
  api_service:
    image: mcr.microsoft.com/devcontainers/rust:latest
    depends_on:
      - kafka
      - zookeeper
      - db
    volumes:
      - ./api_service:/api_service
    ports:
      - 8000:8000
    working_dir: /api_service
    command: ["cargo", "run"]
  event_processing_service:
    image: mcr.microsoft.com/devcontainers/rust:latest
    depends_on:
      - kafka
      - zookeeper
      - db
    volumes:
      - ./event_processing_service:/event_processing_service
    working_dir: /event_processing_service
    command: ["cargo", "run"]
  kafka:
    image: confluentinc/cp-kafka:latest
    environment:
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_CREATE_TOPICS: "orders:1:1"
    depends_on:
      - zookeeper
    ports:
      - 9092:9092
  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: mydb
      POSTGRES_USER: user
      POSTGRES_PASSWORD: aaabbbccc
    volumes:
      - ./postgresql/:/docker-entrypoint-initdb.d/
